"""Generate per-org scan report scaffolds.

Honesty rule: a scaffold contains NO repo names, star counts, or findings —
this script has not scanned anything. Live numbers only ever come from
`scanner/scanner.py`, which overwrites these files with real GitHub data.
(The previous version hard-coded invented "repo1 ⭐ 10000 / repo2 ⭐ 8000"
rows that read as genuine results.)
"""

import os

from scanner.scanner import CARDANO_ORGS, DONATION_ADDR


def scaffold(org):
    return (
        f"# {org} Scan Report\n\n"
        f"Generated by Cardano AI 24/7 Coder\n\n"
        f"## Top Repos by Stars\n\n"
        f"_Not scanned yet — run `python scanner/scanner.py --org {org}` "
        f"to populate this section with live GitHub data._\n\n"
        f"## Findings\n\n"
        f"No issues fetched yet. Add GITHUB_TOKEN to enable live scan.\n\n"
        f"---\n\n"
        f"Donations: {DONATION_ADDR}\n"
    )


def main():
    os.makedirs("reports", exist_ok=True)
    for org in CARDANO_ORGS:
        with open(f"reports/{org}_report.md", "w") as f:
            f.write(scaffold(org))
    print("report scaffolds generated (no scan data — run scanner/scanner.py for live reports)")


if __name__ == "__main__":
    main()
