orgs = [
    "IntersectMBO","input-output-hk","cardanofoundation","EMURGO","Blockfrost",
    "Minswap","SundaeSwap-finance","WingRiders","MLabsHaskell",
    "midnightntwrk","midnightlabs","welldone-software","tweag","cardano-node","cardano-wallet"
]
addr = "addr1q8hnl6vl5a6k3rw3n5g3jtte696zcl76kfatzv7gpswa9r0dj7fma6klq55y4ffm7tf0em09udnyhuk4ah92pl5x9jpqjae44v"
for org in orgs:
    content = f"# {org} Scan Report\n\nGenerated by Cardano AI 24/7 Coder\n\n## Top Repos by Stars\n\n- repo1 ⭐ 10000\n- repo2 ⭐ 8000\n\n## Findings\n\nNo issues fetched yet. Add GITHUB_TOKEN to enable live scan.\n\n---\n\nDonations: {addr}\n"
    open(f"reports/{org}_report.md","w").write(content)
print("reports generated")
