"""
Cardano GitHub Scanner
Scans Cardano-related orgs for issues and opportunities.
"""

import os
import argparse
import requests
from dotenv import load_dotenv

load_dotenv()
GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")

HEADERS = {"Authorization": f"token {GITHUB_TOKEN}"} if GITHUB_TOKEN else {}

CARDANO_ORGS = [
    # Tier 1 - Core Cardano
    "IntersectMBO",
    "input-output-hk",
    "cardanofoundation",
    "EMURGO",
    "Blockfrost",
    # Tier 2 - Major DEXs / Infra
    "Minswap",
    "SundaeSwap-finance",
    "WingRiders",
    "MLabsHaskell",
    # Tier 3 - Midnight Privacy Sidechain
    "midnightntwrk",
    "midnightlabs",
    # Tier 4 - Ecosystem
    "welldone-software",
    "tweag",
    "cardano-node",
    "cardano-wallet"
]

DONATION_ADDR = "addr1q8hnl6vl5a6k3rw3n5g3jtte696zcl76kfatzv7gpswa9r0dj7fma6klq55y4ffm7tf0em09udnyhuk4ah92pl5x9jpqjae44v"

def list_repos(org):
    url = f"https://api.github.com/orgs/{org}/repos?per_page=100"
    resp = requests.get(url, headers=HEADERS)
    resp.raise_for_status()
    repos = resp.json()
    # sort by stars descending for most popular first
    repos_sorted = sorted(repos, key=lambda r: r.get("stargazers_count",0), reverse=True)
    return repos_sorted

def list_issues(org, repo, label="bug"):
    url = f"https://api.github.com/repos/{org}/{repo}/issues?state=open&labels={label}&per_page=50"
    resp = requests.get(url, headers=HEADERS)
    if resp.status_code != 200:
        return []
    return [{"number": i["number"], "title": i["title"], "url": i["html_url"]} for i in resp.json()]

def scan_org(org):
    print(f"Scanning {org}...")
    try:
        repos = list_repos(org)
    except Exception as e:
        print(f"  Error listing repos: {e}")
        return []
    findings = []
    for repo in repos[:20]:  # limit for demo
        issues = list_issues(org, repo["name"])
        if issues:
            findings.append({"repo": repo["name"], "stars": repo.get("stargazers_count",0), "issues": issues})
    # generate markdown report with donation address
    report_path = f"reports/{org}_report.md"
    os.makedirs("reports", exist_ok=True)
    with open(report_path, "w") as f:
        f.write(f"# {org} Scan Report\n\n")
        f.write(f"Generated by Cardano AI 24/7 Coder\n\n")
        f.write(f"## Top Repos by Stars\n\n")
        for r in repos[:10]:
            f.write(f"- {r['name']} ⭐ {r.get('stargazers_count',0)}\n")
        f.write(f"\n## Findings\n\n")
        for fnd in findings:
            f.write(f"### {fnd['repo']} ⭐ {fnd['stars']}\n")
            for iss in fnd['issues'][:5]:
                f.write(f"- #{iss['number']} {iss['title']} - {iss['url']}\n")
        f.write(f"\n---\n\nDonations: {DONATION_ADDR}\n")
    print(f"  Report written to {report_path}")
    return findings

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--org", help="Specific org to scan")
    args = parser.parse_args()
    orgs = [args.org] if args.org else CARDANO_ORGS
    for org in orgs:
        findings = scan_org(org)
        print(f"{org}: {len(findings)} repos with open bugs")

if __name__ == "__main__":
    main()
