"""
Cardano GitHub Scanner
Scans Cardano-related orgs for issues and opportunities.
"""

import os
import argparse
import requests
from dotenv import load_dotenv

load_dotenv()
GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")

# Every HTTP call carries a timeout so a hung connection can never stall
# the unattended (scheduled / 24-7) scan forever.
REQUEST_TIMEOUT = 30
API_BASE = "https://api.github.com"

CARDANO_ORGS = [
    # Tier 1 - Core Cardano
    "IntersectMBO",
    "input-output-hk",
    "cardano-foundation",  # listed as "cardanofoundation" before — that org 404s; this is the real slug
    "EMURGO",
    "Blockfrost",
    # Tier 2 - Major DEXs / Infra
    "Minswap",
    "SundaeSwap-finance",
    "WingRiders",
    "mlabs-haskell",  # listed as "MLabsHaskell" before — that org 404s; this is the real slug
    # Tier 3 - Midnight Privacy Sidechain
    "midnightntwrk",
    "midnightlabs",
    # Tier 4 - Ecosystem
    "welldone-software",
    "tweag",
    # (cardano-node / cardano-wallet used to be listed here, but they are
    # repositories, not orgs — the org endpoint 404s on both, so every scan
    # wasted a call and logged an error. Their issues are already covered
    # via the IntersectMBO / cardano-foundation org scans.)
]

DONATION_ADDR = "addr1q8hnl6vl5a6k3rw3n5g3jtte696zcl76kfatzv7gpswa9r0dj7fma6klq55y4ffm7tf0em09udnyhuk4ah92pl5x9jpqjae44v"


def _headers():
    """Auth headers, read at call time so tests/imports see the current env."""
    token = os.getenv("GITHUB_TOKEN", GITHUB_TOKEN)
    return {"Authorization": f"token {token}"} if token else {}


def _get_json(url, params=None):
    resp = requests.get(url, headers=_headers(), params=params, timeout=REQUEST_TIMEOUT)
    resp.raise_for_status()
    return resp.json()


def list_repos(org):
    """All repos in the org, most-starred first.

    Follows the GitHub API pagination — the previous single-page fetch
    silently dropped every repo past the first 100, so the "top repos by
    stars" report could miss an org's most popular projects entirely.
    """
    repos = []
    page = 1
    while True:
        batch = _get_json(f"{API_BASE}/orgs/{org}/repos", params={"per_page": 100, "page": page})
        repos.extend(batch)
        if len(batch) < 100:
            break
        page += 1
    # sort by stars descending for most popular first
    return sorted(repos, key=lambda r: r.get("stargazers_count", 0), reverse=True)


def list_issues(org, repo, label="bug"):
    """Open issues carrying `label` in one repo.

    The GitHub issues endpoint also returns pull requests; those carry a
    `pull_request` key and are filtered out so findings are real issues.
    """
    try:
        items = _get_json(
            f"{API_BASE}/repos/{org}/{repo}/issues",
            params={"state": "open", "labels": label, "per_page": 50},
        )
    except requests.RequestException as e:
        print(f"  Warning: could not list issues for {org}/{repo}: {e}")
        return []
    return [
        {"number": i["number"], "title": i["title"], "url": i["html_url"]}
        for i in items
        if "pull_request" not in i
    ]


def _positive_int(value):
    """argparse type for --max-repos: must be a positive integer.

    Without this, --max-repos -1 was accepted and Python slice semantics
    turned repos[:-1] into "scan all but the last repo" — a silently
    wrong scan — and --max-repos 0 scanned nothing while the run still
    reported success.
    """
    try:
        ivalue = int(value)
    except (TypeError, ValueError):
        raise argparse.ArgumentTypeError(f"{value!r} is not an integer")
    if ivalue < 1:
        raise argparse.ArgumentTypeError(f"--max-repos must be at least 1, got {ivalue}")
    return ivalue


def scan_org(org, label="bug", max_repos=20):
    if not isinstance(max_repos, int) or max_repos < 1:
        raise ValueError(f"max_repos must be a positive integer, got {max_repos!r}")
    print(f"Scanning {org}...")
    try:
        repos = list_repos(org)
    except Exception as e:
        print(f"  Error listing repos: {e}")
        return []
    findings = []
    for repo in repos[:max_repos]:
        issues = list_issues(org, repo["name"], label=label)
        if issues:
            findings.append({"repo": repo["name"], "stars": repo.get("stargazers_count", 0), "issues": issues})
    # generate markdown report with donation address
    report_path = f"reports/{org}_report.md"
    os.makedirs("reports", exist_ok=True)
    with open(report_path, "w") as f:
        f.write(f"# {org} Scan Report\n\n")
        f.write(f"Generated by Cardano AI 24/7 Coder\n\n")
        f.write(f"## Top Repos by Stars\n\n")
        for r in repos[:10]:
            f.write(f"- {r['name']} ⭐ {r.get('stargazers_count', 0)}\n")
        f.write(f"\n## Findings\n\n")
        if not findings:
            f.write(f"No open issues with the `{label}` label in the top {max_repos} repos.\n")
        for fnd in findings:
            f.write(f"### {fnd['repo']} ⭐ {fnd['stars']}\n")
            for iss in fnd['issues'][:5]:
                f.write(f"- #{iss['number']} {iss['title']} - {iss['url']}\n")
        f.write(f"\n---\n\nDonations: {DONATION_ADDR}\n")
    print(f"  Report written to {report_path}")
    return findings


def main(argv=None):
    parser = argparse.ArgumentParser(description="Scan Cardano GitHub orgs for labelled open issues.")
    parser.add_argument("--org", help="Specific org to scan (default: all known Cardano/Midnight orgs)")
    parser.add_argument("--label", default="bug", help="Issue label to look for (default: bug)")
    parser.add_argument("--max-repos", type=_positive_int, default=20,
                        help="How many of each org's top repos to scan (default: 20)")
    args = parser.parse_args(argv)
    orgs = [args.org] if args.org else CARDANO_ORGS
    for org in orgs:
        findings = scan_org(org, label=args.label, max_repos=args.max_repos)
        print(f"{org}: {len(findings)} repos with open {args.label} issues")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
